### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-factory-for-polyfill#2]
The goal of this library is to provide a `.factoryFor` implementation that is as close as possible to the one in Ember 2.12+.  There are obviously some things that fall short (e.g. it is impossible to prevent double extend when using `.factoryFor` in Ember versions prior to 2.12), but every attempt was made to be true to the original RFC.

I'd like to get some review on this from the following folks that were involved in the original implementation of this feature in Ember 2.12+:

- [x] @stefanpenner
- [ ] @mixonic
- [x] @chadhietala

The primary polyfill is located at [vendor/ember-factory-for-polyfill/index.js](https://github.com/rwjblue/ember-factory-for-polyfill/blob/master/vendor/ember-factory-for-polyfill/index.js).

**Comment by stefanpenner** [comment]
Questions:
* is https://github.com/rwjblue/ember-factory-for-polyfill/blob/master/index.js#L23 to emulate a highlander dependency?
* should the following directories by deleted `addon` `app`
* do we strip `Ember.runInDebug` from vendor code? https://github.com/rwjblue/ember-factory-for-polyfill/blob/master/vendor/ember-factory-for-polyfill/index.js#L22

**Comment by rwjblue** [comment]
> is https://github.com/rwjblue/ember-factory-for-polyfill/blob/master/index.js#L23 to emulate a highlander dependency?

No, it is to ensure that `this.import` is present (ember-cli addons have only had it since ember-cli@2.7).

> should the following directories by deleted addon app

Yep! Will remove.

> do we strip Ember.runInDebug from vendor code?

It is not stripped, but `Ember.runInDebug === function() { };` in production versions so the code is never ran.

**Comment by stefanpenner** [comment]
> is https://github.com/rwjblue/ember-factory-for-polyfill/blob/master/index.js#L23 to emulate a highlander dependency?
> No, it is to ensure that this.import is present (ember-cli addons have only had it since ember-cli@2.7).

Ah ok. I think we should explore higlander stuff in the next month or so. (but obviously wont block this one)



> do we strip Ember.runInDebug from vendor code?
> It is not stripped, but Ember.runInDebug === function() { }; in production versions so the code is never ran.

Seems fine for now.

**Comment by rwjblue** [comment]
>  I think we should explore higlander stuff in the next month or so. 

Totally agreed.

**Comment by chadhietala** [comment]
Nothing else to add. 👍
