### ISSUE TITLE
Do we support Ember 2.0 - 2.2?

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-factory-for-polyfill#4]
Right now the `Ember.getOwner` functionality in Ember < 2.3 is provided by `ember-getowner-polyfill`.  We _could_ make that addon add the `factoryFor` implementation, but it is slightly annoying since we'd have to duplicate a bunch of the test setup and whatnot.

**Comment by offirgolan** [comment]
@rwjblue just out of curiosity, why not just scratch this addon and place the factoryFor code in `ember-getowner-polyfill`? That way, whatever addon installs that polyfill, it will be guaranteed that the API structure to access the owner AND interacting with the owner is the same throughout all Ember versions.

**Comment by rwjblue** [comment]
@offirgolan - I completely agree that ember-getowner-polyfill needs to use the implementation for factoryFor that I have implemented here. The reason we need two addons though is that they both "no op" themselves at different points, `ember-getowner-polyfill` makes itself inert when the consuming app's ember version is 2.3 or higher, whereas this addon needs to operate on 2.3 through 2.11.  

Thank you for commenting here though, I think your comment made it clear how to setup the dependencies correctly (and that I have them wrong at the moment).

**Comment by offirgolan** [comment]
> The reason we need two addons though is that they both "no op" themselves at different points, ember-getowner-polyfill makes itself inert when the consuming app's ember version is 2.3 or higher, whereas this addon needs to operate on 2.3 through 2.11.

That I understand, but the decision on whether to import the polyfill for both of these addons occurs in the same `included` step of the index.js. In theory, couldnt you move this polyfill to `ember-getowner-polyfill` and in the included step (after the existing owner polyfill) make a check if ember is > 2.3 and < 2.11 and if so, import this polyfill as well?

> Thank you for commenting here though, I think your comment made it clear how to setup the dependencies correctly 

No problem! Just trying to probe your brain a bit 😛

**Comment by rwjblue** [comment]
> In theory, couldnt you move this polyfill to ember-getowner-polyfill and in the included step (after the existing owner polyfill) make a check if ember is > 2.3 and < 2.11 and if so, import this polyfill as well?

Yep, absolutely! But if that were the only mechanism to get the factory for polyfill, then there would be no way to create an addon that assumed Ember 2.4+ only (I think current LTS and prior LTS is probably the right choice for any addons newly created).  

In the end, the lines between the two are fairly blurry.  I definitely still want two addons, where including `ember-getowner-polyfill` automatically gives you this one (my plan is to make `ember-getowner-polyfill` depend on `ember-factory-for-polyfill`), and including `ember-factory-for-polyfill` gives you just the `owner.factoryFor` bits.

**Comment by offirgolan** [comment]
Ah okay that makes a lot more sense. Thanks for the clarification 😄 !

**Comment by rwjblue** [comment]
OK, this is landed in https://github.com/rwjblue/ember-getowner-polyfill/pull/18 (which is ember-getowner-polyfill@1.2.0).

**Comment by rwjblue** [comment]
Under test as of https://github.com/rwjblue/ember-factory-for-polyfill/pull/8.
