### ISSUE TITLE
Error: You attempted to access "nodeType" on a factory manager created by container#factoryFor. "nodeType" is not a member of a factory manager.

### ISSUE THREAD

**Issue by lolmaus** [rwjblue/ember-factory-for-polyfill#9]
Originally reported in https://github.com/emberjs/ember.js/issues/15033 and https://github.com/testem/testem/issues/1105.

This error is emitted from [here](https://github.com/rwjblue/ember-factory-for-polyfill/blob/master/vendor/ember-factory-for-polyfill/index.js#L27) when Testem tries to read `value.nodeType`.

```
Error: You attempted to access "nodeType" on a factory manager created by container#factoryFor. "nodeType" is not a member of a factory manager.
    at Object.get (index.js:27)
    at derez (testem.js:70)
    at derez (testem.js:108)
    at derez (testem.js:108)
    at derez (testem.js:108)
    at derez (testem.js:99)
    at derez (testem.js:108)
    at decycle (testem.js:116)
    at Object.serializeMessage (testem.js:906)
    at Object.sendMessageToIframe (testem.js:840)
```

Offending line in Testem: [public/testem/decycle.js#L67](https://github.com/testem/testem/blob/master/public/testem/decycle.js#L67).

I'm unable to create a minimal reproduction scenario, but here are some findings:

```js
// component => a class instance with cyclic references
// component.serialize() => a flat POJO

console.log(comment); // Works. Logs a class instance with cyclic dependencies.
console.log(comment.serialize()); // Works. Logs a flat POJO.
console.log(JSON.stringify(comment.serialize())); // Works, logs a string.
console.log(comment, comment.serialize()); // Crashes with the above error
console.log(comment, JSON.stringify(comment.serialize())); // Also crashes
```

PS You can't even imagine how frustrating this has been. The issue was appearing out of nowhere and then, after hours of frustration, disappearing into the blue. Every time I attributed the issue and fix to an unrelated change in my code. Testem trolled me into becoming one of those [superstitious pigeons](https://en.wikipedia.org/wiki/B._F._Skinner#Superstition_in_the_pigeon): I was resolving it by changing `store.createRecord` to `store.push`, by cleaning `tmp/` and `dist/`, etc.

I would never even consider that the `console.log` invocation itself was the reason. My developer instinct was telling me to ignore it, believing it has no side effects. The stack trace never linked to the offending line, even with the `Async` checkbox enabled.

**Comment by yathi** [comment]
If I had not read this, I would not have realized that the error was because of `console.log`!

**Comment by lolmaus** [comment]
Just ran into this in a new project on latest Ember CLI beta with Mocha. Luckily, this project is open source. I've pushed a reproduction here:

* repo: [bread-maker/bread-maker-ember-frontend](https://github.com/bread-maker/bread-maker-ember-frontend/tree/ember-factory-for-polyfill-issue-9)
* branch: `ember-factory-for-polyfill-issue-9`
* offending line: [tests/acceptance/program-test.js#L37](https://github.com/bread-maker/bread-maker-ember-frontend/blob/ember-factory-for-polyfill-issue-9/tests/acceptance/program-test.js#L37)
* run with: `ember t -s --no-launch -f "should redirect to first program"`
* Travis: https://travis-ci.org/bread-maker/bread-maker-ember-frontend/builds/281625404#L963

@rwjblue This issue has got some upvotes, are you gonna have a look?

**Comment by lolmaus** [comment]
* offending line: [tests/acceptance/program-test.js#L98-L99](https://github.com/bread-maker/bread-maker-ember-frontend/blob/ember-factory-for-polyfill-issue-9/tests/acceptance/program-test.js#L98-L99)

**Comment by lolmaus** [comment]
Previous message edited.

**Comment by rwjblue** [comment]
Sorry for taking so long reviewing this, I must have completely missed it :(

I'm going to close now though, as I work to archive some of these older polyfills...
